// <auto-generated />
using System;
using CoffeeLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeLib.MigrationService.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    partial class CoffeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeLib.Models.AtHomeCoffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AtHomeCoffees");
                });

            modelBuilder.Entity("CoffeeLib.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuItemId = 0,
                            Name = "Hello World Drink"
                        });
                });

            modelBuilder.Entity("CoffeeLib.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CoffeeLib.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtHomeCoffeeId")
                        .HasColumnType("int");

                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AtHomeCoffeeId")
                        .IsUnique();

                    b.HasIndex("DrinkId")
                        .IsUnique();

                    b.HasIndex("FoodId")
                        .IsUnique();

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("CoffeeLib.Models.MenuItemAvailablity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItemAvailablity");
                });

            modelBuilder.Entity("CoffeeLib.Models.MenuItem", b =>
                {
                    b.HasOne("CoffeeLib.Models.AtHomeCoffee", "AtHomeCoffee")
                        .WithOne("MenuItem")
                        .HasForeignKey("CoffeeLib.Models.MenuItem", "AtHomeCoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeLib.Models.Drink", "Drink")
                        .WithOne("MenuItem")
                        .HasForeignKey("CoffeeLib.Models.MenuItem", "DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeLib.Models.Food", "Food")
                        .WithOne("MenuItem")
                        .HasForeignKey("CoffeeLib.Models.MenuItem", "FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtHomeCoffee");

                    b.Navigation("Drink");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("CoffeeLib.Models.MenuItemAvailablity", b =>
                {
                    b.HasOne("CoffeeLib.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemAvailablitys")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("CoffeeLib.Models.AtHomeCoffee", b =>
                {
                    b.Navigation("MenuItem")
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeLib.Models.Drink", b =>
                {
                    b.Navigation("MenuItem")
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeLib.Models.Food", b =>
                {
                    b.Navigation("MenuItem")
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeLib.Models.MenuItem", b =>
                {
                    b.Navigation("MenuItemAvailablitys");
                });
#pragma warning restore 612, 618
        }
    }
}
