// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UILib.Data;

#nullable disable

namespace UILib.MigrationService.Migrations
{
    [DbContext(typeof(UIContext))]
    [Migration("20260315170719_2003155a")]
    partial class _2003155a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UILib.Models.HomeContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HomeContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UILib.Models.HomeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("HomeRowId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeRowId");

                    b.ToTable("HomeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeItemTypeId = 0,
                            HomeRowId = 1,
                            Text = "Hello World"
                        });
                });

            modelBuilder.Entity("UILib.Models.HomeItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomeItemTypes");
                });

            modelBuilder.Entity("UILib.Models.HomeRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeContentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomeContentId");

                    b.ToTable("HomeRows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeContentId = 1
                        });
                });

            modelBuilder.Entity("UILib.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Menu Hello World"
                        });
                });

            modelBuilder.Entity("UILib.Models.MenuGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuId = 1,
                            Name = "MenuGroup Hello World"
                        });
                });

            modelBuilder.Entity("UILib.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoffeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MenuSubGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuSubGroupId");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("UILib.Models.MenuSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuGroupId");

                    b.ToTable("MenuSubGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuGroupId = 1,
                            Name = "MenuSubGroup"
                        });
                });

            modelBuilder.Entity("UILib.Models.HomeItem", b =>
                {
                    b.HasOne("UILib.Models.HomeRow", "HomeRow")
                        .WithMany("HomeItems")
                        .HasForeignKey("HomeRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeRow");
                });

            modelBuilder.Entity("UILib.Models.HomeRow", b =>
                {
                    b.HasOne("UILib.Models.HomeContent", "HomeContent")
                        .WithMany("HomeRows")
                        .HasForeignKey("HomeContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeContent");
                });

            modelBuilder.Entity("UILib.Models.MenuGroup", b =>
                {
                    b.HasOne("UILib.Models.Menu", "Menu")
                        .WithMany("MenuGroups")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("UILib.Models.MenuItem", b =>
                {
                    b.HasOne("UILib.Models.MenuSubGroup", "MenuSubGroup")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuSubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuSubGroup");
                });

            modelBuilder.Entity("UILib.Models.MenuSubGroup", b =>
                {
                    b.HasOne("UILib.Models.MenuGroup", "MenuGroup")
                        .WithMany("MenuSubGroups")
                        .HasForeignKey("MenuGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuGroup");
                });

            modelBuilder.Entity("UILib.Models.HomeContent", b =>
                {
                    b.Navigation("HomeRows");
                });

            modelBuilder.Entity("UILib.Models.HomeRow", b =>
                {
                    b.Navigation("HomeItems");
                });

            modelBuilder.Entity("UILib.Models.Menu", b =>
                {
                    b.Navigation("MenuGroups");
                });

            modelBuilder.Entity("UILib.Models.MenuGroup", b =>
                {
                    b.Navigation("MenuSubGroups");
                });

            modelBuilder.Entity("UILib.Models.MenuSubGroup", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
